const ACCOUNT_OR_PASSWORD_IS_EMPTY = 'ACCOUNT_OR_PASSWORD_IS_EMPTY'
const ACCOUNT_HAS_EXIST = 'ACCOUNT_HAS_EXIST'
const ACCOUNT_IS_NOT_EXIST = 'ACCOUNT_IS_NOT_EXIST'
const PASSWORD_IS_ERROR = 'PASSWORD_IS_ERROR'
const TOKEN_INVALID = 'TOKEN_INVALID'

export { ACCOUNT_OR_PASSWORD_IS_EMPTY, ACCOUNT_HAS_EXIST, ACCOUNT_IS_NOT_EXIST, PASSWORD_IS_ERROR, TOKEN_INVALID }
