const ACCOUNT_OR_PASSWORD_IS_EMPTY = 'ACCOUNT_OR_PASSWORD_IS_EMPTY'
const ACCOUNT_HAS_EXIST = 'ACCOUNT_HAS_EXIST'
const ACCOUNT_IS_NOT_EXIST = 'ACCOUNT_IS_NOT_EXIST'
const PASSWORD_IS_ERROR = 'PASSWORD_IS_ERROR'
const TOKEN_INVALID = 'TOKEN_INVALID'
const NOT_FOUND_MOMENT_ID = 'NOT_FOUND_MOMENT_ID'
const WITHOUT_PERMISSION = 'WITHOUT_PERMISSION'
const LABEL_HAS_EXIST = 'LABEL_HAS_EXIST'

export {
  ACCOUNT_OR_PASSWORD_IS_EMPTY,
  ACCOUNT_HAS_EXIST,
  ACCOUNT_IS_NOT_EXIST,
  PASSWORD_IS_ERROR,
  TOKEN_INVALID,
  NOT_FOUND_MOMENT_ID,
  WITHOUT_PERMISSION,
  LABEL_HAS_EXIST
}
